name: Fix Duplicate IDs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  fix-duplicate-ids:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run fix_ids.py
      run: |
        python fix_ids.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add post/post.json
        git commit -m 'Fix duplicate IDs in post.json'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
