name: Twitter Bot Scheduler

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  workflow_dispatch:  # Allows manual trigger

jobs:
  post-tweets:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask requests_oauthlib APScheduler

    - name: Run Twitter Bot
      env:
        FLASK_SECRET_KEY: ${{ secrets.FLASK_SECRET_KEY }}
        CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
        CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
        ACCESS_TOKEN2: ${{ secrets.ACCESS_TOKEN2 }}
        ACCESS_SECRET2: ${{ secrets.ACCESS_SECRET2 }}
      run: python app.py &

    - name: Wait for post to complete
      run: sleep 60  # Wait for 1 minute to ensure post is completed

    - name: Commit and push if there are changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add posted_history.json
        git commit -m "Update posted history" || echo "No changes to commit"
        git push
